name: StaffTicket
description: Allows your players to submit tickets with bug reports, hacking and so much more.
author: Christopher Nethercott
authors: [Thorin, ThorinDev]
version: ${project.version}
main: github.chriscn.StaffTicket
api-version: 1.16
load: STARTUP
commands:
  ticket:
    usage: /ticket <create/review/assign/resolve> (id)
    aliases: t
  staffticket:
    usage: /staffticket <reload/info>
    aliases: st