name: StaffTicket
description: Allows your players to submit tickets with bug reports, hacking and so much more.
author: Christopher Nethercott
authors: [Thorin, ThorinDev]
version: ${project.version}
main: github.chriscn.StaffTicket
api-version: 1.16
load: STARTUP
commands:
  ticket:
    usage: /ticket
  createticket:
    usage: /createticket <message>
  staffticket:
    usage: /staffticket <reload>
    aliases: st